### ISSUE TITLE
Please create an official PHP Mastodon account

### ISSUE THREAD

**Issue by mlcohen** [php/web-php#829]
This is a very humble request for someone on the PHP team to please setup an official PHP [Mastodon](https://joinmastodon.org/) account. Currently PHP only has a [Twitter/X account](https://twitter.com/official_php). There are many developers who use PHP who would much prefer to follow updates on Mastodon. Since there already exists a PHP Mastodon server (https://phpc.social), an official account could be established there (e.g. official_php@phpc.social). As an official account, it should be properly [verified](https://joinmastodon.org/verification). As well, adding a prominent link to the [php.net website](https://www.php.net) would give the account a lot of visibility. At the moment, php.net only has a link to the official Twitter account.

It should be noted that the PHP Foundation does have an official Mastodon account ([@thephpf@phpc.social](https://phpc.social/@thephpf)) and the foundation's [website](https://thephp.foundation) includes a link to it. The account itself is not verified as the link to it does not include a `rel="me"` attribute nor does the account's profile include a link back to the PHP Foundation website.

**Comment by pronskiy** [comment]
This is the official account https://fosstodon.org/@php
/cc @derickr @ramsey

**Comment by ramsey** [comment]
Thanks for the PR, @abackstrom! I've merged it.

**Comment by mlcohen** [comment]
@ramsey @pronskiy Thanks so much for the response and updates! 👏👏👏 

Who manages the PHP Foundation Mastodon [account](https://phpc.social/@thephpf) @thephpf@phpc.social? It would be great to have that account verified as well. Just need to add `rel="me"` attribute to the Mastodon link and update the account's profile.

<img width="576" alt="Screenshot 2023-11-23 at 12 11 03 PM" src="https://github.com/php/web-php/assets/100445/d1fb32b7-fd8f-4817-97c3-f600bd568121">

<img width="1250" alt="Screenshot 2023-11-23 at 12 13 55 PM" src="https://github.com/php/web-php/assets/100445/7b1ce99f-d688-4a53-8477-44439834afdf">

**Comment by pronskiy** [comment]
@mlcohen, thanks, fixed in https://github.com/ThePHPF/thephp.foundation/commit/9b11193ab8b4a0b24c47aef6830672f354dd1922.

**Comment by mlcohen** [comment]
Now seeing both websites with a `rel="me"` meta link. PHP Foundation [account](https://phpc.social/@thephpf) is showing up as verified; however, the official PHP [account](https://fosstodon.org/@php) still does not appear as verified. Not sure who is managing the PHP account but if someone could re-save the account's profile, that should trigger a link verification and get things in order.

<img width="575" alt="Screenshot 2023-11-23 at 12 46 58 PM" src="https://github.com/php/web-php/assets/100445/3230f57c-14f0-4e7e-9d96-dcc0653e5717">

<img width="575" alt="Screenshot 2023-11-23 at 12 45 52 PM" src="https://github.com/php/web-php/assets/100445/f757b1d5-08b2-4f2b-99a0-ed6be236343e">

**Comment by mlcohen** [comment]
Can confirm that both accounts are now verified ✅

Big thanks again to @pronskiy, @ramsey, @abackstrom and @derickr for the timely updates! 💪

<img width="576" alt="Screenshot 2023-11-23 at 4 31 57 PM" src="https://github.com/php/web-php/assets/100445/9de98d41-27b1-48f0-91c7-d05ff969d184">

<img width="578" alt="Screenshot 2023-11-23 at 4 32 16 PM" src="https://github.com/php/web-php/assets/100445/c2ffff3b-2f21-4817-bf1f-c6017f1a048d">
